server:
  port: 8888
  
spring:
  application:
    name: user-service
    
eureka:
  client:
    service-url:
      defaultZone: http://100.36.17.163:9000/eureka
  instance:
    lease-expiration-duration-in-seconds: 10
    lease-renewal-interval-in-seconds: 5
      